---
- name: Copy updates to remote devices
  hosts: all
  tasks:
    - name: Copy updates folder to remote device
      ansible.builtin.copy:
        src: "{{ src_update_path }}"
        dest: "{{ dest_update_path }}"
        remote_src: no
        owner: remote_user
        group: remote_group
        mode: '0755'
