---
- name: Copy updates to remote devices
  hosts: all
  tasks:
    - name: Copy updates folder to remote device
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../updates/v1.0.1/"
        dest: "/home/test"
        remote_src: no
        owner: remote_user
        group: remote_group
        mode: '0755'
